### ISSUE TITLE
undefined is not an object (evaluating _reactNativeReAnimated.Transition.Together)

### ISSUE THREAD

**Issue by nwaughachukwuma** [react-navigation/react-navigation-animated-switch#3]
I keep getting this error whether am using the transition property or not:
`undefined is not an object (evaluating _reactNativeReAnimated.Transition.Together)`

**Comment by brentvatne** [comment]
you need to install the latest version of reanimated

**Comment by vladb95** [comment]
Hi, I'm sorry, but which version of reanimated would be installed, because for current version (1.0.1) it doesn't work?

**Comment by brentvatne** [comment]
@vladb95 - yes it does. any version > 1.0.0 and it will work. this lib just depends on the Transitioning API which was added in 1.0.0.
